- hosts: main

  vars_files:
    - secrets.yml

  roles:
    - role: security
      become: yes
      tags:
        - root
        - security

    - role: tweaks
      become: yes
      tags:
        - root
        - tweaks

    - role: docker
      become: yes
      tags:
        - root
        - docker

    - role: services
      tags:
        - services
